version: '3.8'
services:
  webserver:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - 5173:5173
    depends_on:
      - api
  api:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./credentials/service_account_key.json:/app/service_account_key.json
    ports:
      - 8080:8080
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service_account_key.json
