version: '3.8'
volumes:
  node_modules:
services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=airflow
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    depends_on:
      - backend
    ports:
      - 5173:5173
    restart: always
  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./credentials/service_account_key.json:/app/service_account_key.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service_account_key.json
      - SQLALCHEMY_DATABASE_URL=postgresql+psycopg2://postgres:postgres@postgres:5432/redflags
    depends_on:
      - postgres
    ports:
      - 8080:8080
    restart: always