runtime: python311

api_version: 1

env_variables:
  PYTHONUNBUFFERED: 1
# error_handlers:
# handlers

instance_class: F1

entrypoint: gunicorn --workers 2 --worker-class uvicorn.workers.UvicornWorker main:app

# GCP App Engine
# The number of workers must match the instance class
# | Instance Class | Workers |
#|-----------------|---------|
#| F1	           |    2    |
#| F2	           |    4    |
#| F4	           |    8    |
#| F4_1G           |    8    |
#| B1	           |    2    |
#| B2	           |    4    |
#| B4	           |    8    |
#| B4_1G	       |    8    |
#| B8	           |    8    |
